teams = {
    'Hawks': '/teams/ATL/',
    'Celtics': '/teams/BOS/', 
    'Nets': '/teams/BRK/', 
    'Hornets': '/teams/CHO/', 
    'Bulls': '/teams/CHI/', 
    'Cavaliers': '/teams/CLE/', 
    'Mavericks': '/teams/DAL/', 
    'Nuggets': '/teams/DEN/', 
    'Pistons': '/teams/DET/', 
    'Warriors': '/teams/GSW/', 
    'Rockets': '/teams/HOU/', 
    'Pacers': '/teams/IND/', 
    'Clippers': '/teams/LAC/', 
    'Lakers': '/teams/LAL/', 
    'Grizzlies': '/teams/MEM/', 
    'Heat': '/teams/MIA/', 
    'Bucks': '/teams/MIL/', 
    'Timberwolves': '/teams/MIN/', 
    'Pelicans': '/teams/NOP/', 
    'Knicks': '/teams/NYK/', 
    'Thunder': '/teams/OKC/', 
    'Magic': '/teams/ORL/', 
    '76ers': '/teams/PHI/', 
    'Suns': '/teams/PHO/', 
    'Trail Blazers': '/teams/POR/', 
    'Kings': '/teams/SAC/', 
    'Spurs': '/teams/SAS/', 
    'Raptors': '/teams/TOR/', 
    'Jazz': '/teams/UTA/', 
    'Wizards': '/teams/WAS/'
    }